name: 報告・お問い合わせ
description: 不具合の報告や、画像を含めた詳細な相談はこちらから
body:
  - type: dropdown
    id: category
    attributes:
      label: カテゴリー
      options:
        - インストール
        - 使い方
        - 不具合報告
        - その他
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 詳細内容
      description: ここに詳しい内容を書いてください。画像はここに直接ドラッグ＆ドロップすればアップロードできます。
      placeholder: どのような状況で問題が発生しましたか？
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: 実行環境
      placeholder: OSの種類や、使っているBotのバージョンなど
